version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1-browsers
        environment:
          NO_SANDBOX: true
    steps:
      - checkout
      - run:
          command: make
      - persist_to_workspace:
          root: .
          paths:
            - public


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          context: ipfs-dns-deploy
          requires:
            - build
